version: '2'
services:
    service1:
        image: seuslab/service1
        volumes:
            - '/work/other/seuslab/data:/data'
        depends_on:
            - service2
            - redis
        environment:
            - DATA_PATH=/data
            - SERVICE2_NAME=service2
            - SERVICE2_PORT=8787
    service2:
        image: seuslab/service2
        depends_on:
            - postgresql
            - redis
        environment:
            - SERVICE_PORT=8787
            - DATABASE_HOST=postgresql
            - DATABASE_PORT=5432
            - DATABASE_NAME=seuslab
            - DATABASE_USER=seuslab
            - DATABASE_PASSWORD=seuslab
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    postgresql:
        extends:
            file: postgresql.yml
            service: postgresql
    redis:
        extends:
            file: redis.yml
            service: redis
